language: python

addons:
  apt:
    packages:
    - wget

matrix:
  include:
    - python: 2.7
    - python: pypy-5.3.1
    - python: 3.4
    - python: pypy3.3-5.2-alpha1
    - python: 3.4
      env: TOX_ENV=docs
    - python: 3.4
      env: TOX_ENV=flake8
    - python: 3.4
      env: TOX_ENV=coverage

install:
    - pip install tox
    - pip install coveralls
    - mkdir influxdb_install
    - wget https://dl.influxdata.com/influxdb/releases/influxdb_0.13.0_amd64.deb
    - dpkg -x influxdb*.deb influxdb_install
script:
    - export INFLUXDB_PYTHON_INFLUXD_PATH=$(pwd)/influxdb_install/usr/bin/influxd
    - tox
after_success:
    - if [ "$TOX_ENV" == "coverage" ] ; then coveralls; fi
notifications:
    email: false

sudo: false

# Travis caching
cache: false
#  directories:
#    - $HOME/.cache/pip
#before_cache:
#  - rm -f $HOME/.cache/pip/log/debug.log
