language: python

addons:
  apt:
    packages:
    - wget

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: pypy
      env: TOX_ENV=pypy
    - python: 3.4
      env: TOX_ENV=py34
    - python: pypy3
      env: TOX_ENV=pypy3
    - python: 3.4
      env: TOX_ENV=docs
    - python: 3.4
      env: TOX_ENV=flake8
    - python: 3.4
      env: TOX_ENV=coverage

install:
    - pip install tox
    - pip install coveralls
    - mkdir influxdb_install
    - wget https://dl.influxdata.com/influxdb/releases/influxdb_0.13.0_amd64.deb
    - dpkg -x influxdb*.deb influxdb_install
script:
    - export INFLUXDB_PYTHON_INFLUXD_PATH=$(pwd)/influxdb_install/usr/bin/influxd
    - tox
after_failure:
    - cat /home/travis/build/influxdata/influxdb-python/.tox/coverage/log/coverage-0.log
    - cat /home/travis/build/influxdata/influxdb-python/.tox/coverage/log/coverage-1.log
    - cat /home/travis/build/influxdata/influxdb-python/.tox/docs/log/docs-0.log
    - cat /home/travis/build/influxdata/influxdb-python/.tox/flake8/log/flake8-0.log
after_success:
    - if [ "$TOX_ENV" == "coverage" ] ; then coveralls; fi
notifications:
    email: false

sudo: false

# Travis caching
cache: false
#  directories:
#    - $HOME/.cache/pip
#before_cache:
#  - rm -f $HOME/.cache/pip/log/debug.log
